version: '3.8'

services:
  db:
    image: mysql
    container_name: db
    ports:
      - 3306:3306 # HOST:CONTAINER
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=app_session
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db:/var/lib/mysql
